import { acceptsApiKeys, customerRoutePolicies, defineRoutePolicies, permissions } from "@__TRESTLE_PROJECT_NAME__/authz";

const platform = (method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE", path: string, permission: string) => ({ method, path, audience: "platform" as const, permission });

/** Every admin Worker route and the platform permission its handler enforces. */
export const platformRoutePolicies = defineRoutePolicies(permissions, [
  { method: "GET", path: "/api/auth/*", public: true, audience: "public" },
  { method: "POST", path: "/api/auth/*", public: true, audience: "public" },
  { method: "GET", path: "/api/admin/health/live", public: true, audience: "public" },
  { method: "GET", path: "/api/admin/session", audience: "session" },
  { method: "DELETE", path: "/api/admin/support/sessions/current", audience: "session" },
  platform("GET", "/api/admin/capabilities", "platform.overview.read"),
  platform("GET", "/api/admin/overview", "platform.overview.read"),
  platform("GET", "/api/admin/health", "platform.overview.read"),
  platform("GET", "/api/admin/organizations", "platform.organizations.read"),
  platform("GET", "/api/admin/organizations/:id", "platform.organizations.read"),
  platform("GET", "/api/admin/support/profiles", "platform.support.enter_tenant"),
  platform("POST", "/api/admin/support/preview", "platform.support.enter_tenant"),
  platform("POST", "/api/admin/support/sessions", "platform.support.enter_tenant"),
  platform("GET", "/api/admin/support/sessions", "platform.support.read"),
  platform("GET", "/api/admin/support/sessions/:id", "platform.support.read"),
  platform("POST", "/api/admin/support/sessions/:id/revoke", "platform.support.revoke"),
  platform("GET", "/api/admin/support/tenant", "platform.support.enter_tenant"),
  platform("GET", "/api/admin/webhooks", "platform.webhooks.read"),
  platform("GET", "/api/admin/webhooks/:id/deliveries", "platform.webhooks.read"),
  platform("POST", "/api/admin/webhooks/:id/disable", "platform.webhooks.disable"),
  platform("POST", "/api/admin/webhook-deliveries/:id/replay", "platform.webhooks.replay"),
  platform("POST", "/api/admin/entitlements/:organizationId/compare", "platform.subscriptions.read"),
  platform("GET", "/api/admin/auth-policy", "platform.auth_policy.read"),
  platform("POST", "/api/admin/auth-policy/drafts", "platform.auth_policy.manage"),
  platform("PUT", "/api/admin/auth-policy/draft", "platform.auth_policy.manage"),
  platform("DELETE", "/api/admin/auth-policy/draft", "platform.auth_policy.manage"),
  platform("POST", "/api/admin/auth-policy/draft/activate", "platform.auth_policy.manage"),
  platform("POST", "/api/admin/auth-policy/versions/:version/rollback", "platform.auth_policy.manage"),
  platform("GET", "/api/admin/billing-mappings", "platform.plans.read"),
  platform("POST", "/api/admin/billing-mappings", "platform.plans.manage"),
  platform("POST", "/api/admin/billing-mappings/create", "platform.plans.manage"),
  platform("POST", "/api/admin/billing-mappings/:id/verify", "platform.plans.manage"),
  platform("DELETE", "/api/admin/billing-mappings/:id", "platform.plans.manage"),
  platform("GET", "/api/admin/notification-streams", "platform.notifications.read"),
  platform("GET", "/api/admin/notification-streams/:type", "platform.notifications.read"),
  platform("POST", "/api/admin/notification-streams", "platform.notification_streams.manage"),
  platform("PATCH", "/api/admin/notification-streams/:type", "platform.notification_streams.manage"),
  platform("PUT", "/api/admin/notification-streams/:type/draft", "platform.notification_streams.manage"),
  platform("DELETE", "/api/admin/notification-streams/:type/draft", "platform.notification_streams.manage"),
  platform("POST", "/api/admin/notification-streams/:type/drafts", "platform.notification_streams.manage"),
  platform("POST", "/api/admin/notification-streams/:type/publish", "platform.notification_streams.manage"),
  platform("POST", "/api/admin/notification-streams/:type/archive", "platform.notification_streams.manage"),
  platform("POST", "/api/admin/notification-streams/:type/restore", "platform.notification_streams.manage"),
  platform("POST", "/api/admin/notification-streams/:type/preview", "platform.notifications.read"),
  platform("POST", "/api/admin/notification-streams/:type/test", "platform.notification_streams.manage"),
  platform("GET", "/api/admin/notifications", "platform.notifications.read"),
  platform("GET", "/api/admin/notifications/:id", "platform.notifications.read"),
  platform("POST", "/api/admin/notification-deliveries/:id/retry", "platform.notifications.manage"),
  platform("POST", "/api/admin/notification-deliveries/:id/cancel", "platform.notifications.manage"),
  platform("GET", "/api/admin/users", "platform.users.read"),
  platform("POST", "/api/admin/users/:id/suspend", "platform.users.suspend"),
  platform("POST", "/api/admin/users/:id/restore", "platform.users.suspend"),
  platform("POST", "/api/admin/users/:id/sessions/revoke", "platform.sessions.revoke"),
  platform("GET", "/api/admin/features", "platform.plans.read"),
  platform("GET", "/api/admin/plans", "platform.plans.read"),
  platform("POST", "/api/admin/plans/:plan/versions", "platform.plans.manage"),
  platform("PATCH", "/api/admin/plans/:plan/versions/:version", "platform.plans.manage"),
  platform("POST", "/api/admin/plans/:plan/versions/:version/transition", "platform.plans.manage"),
  platform("GET", "/api/admin/subscriptions", "platform.subscriptions.read"),
  platform("GET", "/api/admin/subscriptions/:organizationId", "platform.subscriptions.read"),
  platform("POST", "/api/admin/subscriptions/:organizationId/overrides", "platform.subscriptions.manage"),
  platform("DELETE", "/api/admin/subscriptions/:organizationId/overrides/:id", "platform.subscriptions.manage"),
  platform("POST", "/api/admin/subscriptions/:organizationId/changes", "platform.subscriptions.manage"),
  platform("POST", "/api/admin/subscriptions/:organizationId/reconcile", "platform.reconciliation.run"),
  platform("GET", "/api/admin/entitlements/:organizationId", "platform.subscriptions.read"),
  platform("POST", "/api/admin/entitlements/simulate", "platform.plans.read"),
  platform("GET", "/api/admin/permissions", "platform.roles.read"),
  platform("GET", "/api/admin/roles", "platform.roles.read"),
  platform("GET", "/api/admin/route-policies", "platform.roles.read"),
  platform("GET", "/api/admin/application-role-assignments", "platform.roles.read"),
  platform("GET", "/api/admin/platform-roles", "platform.roles.read"),
  platform("POST", "/api/admin/platform-roles", "platform.roles.manage"),
  platform("DELETE", "/api/admin/platform-roles/:userId/:role", "platform.roles.manage"),
  platform("POST", "/api/admin/access/explain", "platform.access.explain"),
  platform("GET", "/api/admin/service-accounts", "platform.machine_access.read"),
  platform("POST", "/api/admin/service-accounts/:id/suspend", "platform.machine_access.revoke"),
  platform("GET", "/api/admin/api-keys", "platform.machine_access.read"),
  platform("POST", "/api/admin/api-keys/:id/revoke", "platform.machine_access.revoke"),
  platform("POST", "/api/admin/plans", "platform.plans.manage"),
  platform("GET", "/api/admin/webhook-event-types", "platform.webhooks.read"),
  platform("GET", "/api/admin/webhooks/:id", "platform.webhooks.read"),
  platform("POST", "/api/admin/webhooks", "platform.webhooks.manage"),
  platform("PATCH", "/api/admin/webhooks/:id", "platform.webhooks.manage"),
  platform("POST", "/api/admin/webhooks/:id/pause", "platform.webhooks.manage"),
  platform("POST", "/api/admin/webhooks/:id/resume", "platform.webhooks.manage"),
  platform("POST", "/api/admin/webhooks/:id/test", "platform.webhooks.manage"),
  platform("POST", "/api/admin/webhooks/:id/rotate-secret", "platform.webhooks.manage"),
  platform("DELETE", "/api/admin/webhooks/:id", "platform.webhooks.manage"),
  platform("GET", "/api/admin/catalog", "platform.roles.read"),
  platform("GET", "/api/admin/catalog/key-rules", "platform.roles.read"),
  platform("GET", "/api/admin/catalog/roles/:plane/:key/assignments", "platform.roles.read"),
  platform("GET", "/api/admin/catalog/permissions/:code/references", "platform.roles.read"),
  platform("POST", "/api/admin/catalog/permissions", "platform.access_catalog.manage"),
  platform("PATCH", "/api/admin/catalog/permissions/:code", "platform.access_catalog.manage"),
  platform("POST", "/api/admin/catalog/permissions/:code/deprecate", "platform.access_catalog.manage"),
  platform("POST", "/api/admin/catalog/permissions/:code/restore", "platform.access_catalog.manage"),
  platform("DELETE", "/api/admin/catalog/permissions/:code", "platform.access_catalog.manage"),
  platform("POST", "/api/admin/catalog/roles", "platform.access_catalog.manage"),
  platform("PATCH", "/api/admin/catalog/roles/:plane/:key", "platform.access_catalog.manage"),
  platform("POST", "/api/admin/catalog/roles/:plane/:key/archive", "platform.access_catalog.manage"),
  platform("POST", "/api/admin/catalog/roles/:plane/:key/restore", "platform.access_catalog.manage"),
  platform("DELETE", "/api/admin/catalog/roles/:plane/:key", "platform.access_catalog.manage"),
  platform("POST", "/api/admin/organizations/:organizationId/members/:memberId/organization-roles", "platform.tenant_access.assign"),
  platform("POST", "/api/admin/organizations/:organizationId/users/:userId/application-roles", "platform.tenant_access.assign"),
  platform("GET", "/api/admin/service-accounts/:id", "platform.machine_access.read"),
  platform("POST", "/api/admin/service-accounts", "platform.machine_access.manage"),
  platform("PATCH", "/api/admin/service-accounts/:id", "platform.machine_access.manage"),
  platform("POST", "/api/admin/service-accounts/:id/reactivate", "platform.machine_access.manage"),
  platform("DELETE", "/api/admin/service-accounts/:id", "platform.machine_access.manage"),
  platform("GET", "/api/admin/api-key-scopes", "platform.machine_access.read"),
  platform("GET", "/api/admin/api-keys/:id", "platform.machine_access.read"),
  platform("POST", "/api/admin/api-keys", "platform.machine_access.manage"),
  platform("POST", "/api/admin/api-keys/:id/rotate", "platform.machine_access.manage"),
  platform("POST", "/api/admin/api-keys/:id/replace", "platform.machine_access.manage"),
  platform("GET", "/api/admin/email", "platform.email.read"),
  platform("GET", "/api/admin/email/:id", "platform.email.read"),
  platform("GET", "/api/admin/identity", "platform.identity.read"),
  platform("GET", "/api/admin/async", "platform.jobs.read"),
  platform("POST", "/api/admin/async/dead/:id/redrive", "platform.jobs.redrive"),
  platform("GET", "/api/admin/artifacts", "platform.artifacts.read"),
  platform("GET", "/api/admin/audit", "platform.audit.read"),
  platform("GET", "/api/admin/audit/:id", "platform.audit.read"),
]);

/**
 * Routes that act inside a tenant during a support session. They require
 * organization or application permissions, which only the session's frozen
 * profile snapshot can supply, and never reveal secrets.
 */
export const supportRoutePolicies = defineRoutePolicies(permissions, [
  { method: "GET", path: "/api/admin/support/tenant/members", audience: "tenant", permission: "organization.members.read" },
  { method: "GET", path: "/api/admin/support/tenant/webhooks", audience: "tenant", permission: "organization.webhooks.read" },
  { method: "GET", path: "/api/admin/support/tenant/webhooks/:id", audience: "tenant", permission: "organization.webhooks.read" },
  { method: "POST", path: "/api/admin/support/tenant/webhooks/:id/pause", audience: "tenant", permission: "organization.webhooks.manage" },
  { method: "POST", path: "/api/admin/support/tenant/webhooks/:id/resume", audience: "tenant", permission: "organization.webhooks.manage" },
  { method: "POST", path: "/api/admin/support/tenant/webhooks/:id/test", audience: "tenant", permission: "organization.webhooks.manage" },
  { method: "POST", path: "/api/admin/support/tenant/webhook-deliveries/:id/replay", audience: "tenant", permission: "organization.webhooks.replay" },
  { method: "GET", path: "/api/admin/support/tenant/notification-deliveries", audience: "tenant", permission: "organization.notifications.read" },
  { method: "GET", path: "/api/admin/support/tenant/audit", audience: "tenant", permission: "organization.audit.read" },
]);

export const adminRoutePolicies = {
  customer: customerRoutePolicies.map((route) => ({ ...route, acceptsApiKeys: acceptsApiKeys(permissions, route) })),
  admin: platformRoutePolicies,
  support: supportRoutePolicies,
};
